#!/bin/bash

HOST=$1


RC=`ssh djwillia@$1 "cat ~/.bashrc" | grep -o "DJWILLIA EMACS TRAMP"`

if [[ "X$RC" != "XDJWILLIA EMACS TRAMP" ]]; then
    ssh djwillia@$1 "echo -e \"# DJWILLIA EMACS TRAMP\n. ~/.bash_emacs\" >> .bashrc"
fi

MYHOST=`hostname -f`
IP=`ping -c 1 $MYHOST 2>&1 |grep -o "from [^:]*" |sed s/"from "//`
cat remote/emacsclient-tramp-find |sed s/"EMACSSERVER="/"EMACSSERVER=$IP"/ > /tmp/emacsclient-tramp-find
chmod u+x /tmp/emacsclient-tramp-find

# set up keys?

ssh djwillia@$1 "mkdir -p ~/bin"
scp remote/.bash_emacs djwillia@$1:
scp /tmp/emacsclient-tramp-find djwillia@$1:bin/
scp remote/emacsclient-tramp-sudo djwillia@$1:bin/
